# Creating NumPy Arrays

In [1]:
# Installation: pip3 install numpy
#Importing NumPy: import numpy as np

In [3]:
#Using np.array():

import numpy as np

# Create an array from a Python list
my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)
print(my_array)


[1 2 3 4 5]


In [3]:
#Using np.zeros() and np.ones() to create arrays filled with zeros or ones:

import numpy as np

# Create a 1D array of zeros with 5 elements
zeros_array = np.zeros(5)
print(zeros_array)

# Create a 2D array of ones with a shape of (3, 4)
ones_array = np.ones((3, 4))
print(ones_array)


[0. 0. 0. 0. 0.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
#Using np.arange() to create an array with regularly spaced values:
import numpy as np

# Create an array with values from 0 to 9 (exclusive) with a step of 1
arange_array = np.arange(0, 10, 1)
print(arange_array)


[0 1 2 3 4 5 6 7 8 9]


In [11]:
#Using np.linspace() to create an array with evenly spaced values over a specified range:
import numpy as np

# Create an array with 10 evenly spaced values from 0 to 1 (inclusive)
linspace_array = np.linspace(0, 10, 11)
print(linspace_array)


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [14]:
a=10.5
b=11
print(type(a))
print(type(b))

<class 'float'>
<class 'int'>


# Array Operations with NumPy

In [15]:
#Arithmetic Operations

import numpy as np

# Creating two NumPy arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Addition
result_add = arr1 + arr2  # [5, 7, 9]
print(result_add)
# Subtraction
result_sub = arr1 - arr2  # [-3, -3, -3]
print(result_sub)
# Multiplication
result_mul = arr1 * arr2  # [4, 10, 18]
print(result_mul)
# Division
result_div = arr1 / arr2  # [0.25, 0.4, 0.5]
print(result_div)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [16]:
#Element-wise Operations:
import numpy as np

arr = np.array([1, 2, 3])

# Element-wise square
squared = np.square(arr)  # [1, 4, 9]
print(squared)
# Element-wise square root
sqrted = np.sqrt(arr)  # [1.0, 1.41421356, 1.73205081]
print(sqrted)
# Element-wise exponentiation (e^x)
exp_arr = np.exp(arr)  # [2.71828183, 7.3890561, 20.08553692]
print(exp_arr)

[1 4 9]
[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]


In [14]:
'''Broadcasting:
Broadcasting allows NumPy to work with arrays of different shapes during arithmetic operations. 
It automatically expands smaller arrays to match the shape of larger arrays.
'''

'Broadcasting:\nBroadcasting allows NumPy to work with arrays of different shapes during arithmetic operations. \nIt automatically expands smaller arrays to match the shape of larger arrays.\n'

In [15]:
import numpy as np

arr = np.array([1, 2, 3])
scalar = 2

# Broadcasting scalar to the array
result = arr + scalar  # [3, 4, 5]


In [2]:
import numpy as np 
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])  
   
print('First array:')
print(a)
print('\n')  
   
print('Second array:') 
print(b)
print('\n')  
   
print('First Array + Second Array')
print(a + b)

First array:
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]


Second array:
[1. 2. 3.]


First Array + Second Array
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


# Indexing NumPy Arrays:

In [17]:
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Access the first element (index 0)
first_element = arr[0]
print(first_element)  # Output: 1

# Access the third element (index 2)
third_element = arr[2]
print(third_element)  # Output: 3


1
3


# Slicing NumPy Arrays:

In [18]:
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Slice to get elements from index 2 to 5 (exclusive)
sliced_arr = arr[2:5]
print(sliced_arr)  # Output: [3 4 5]

# Slice to get every second element from index 1 to 7
sliced_arr = arr[1:7:2]
print(sliced_arr)  # Output: [2 4 6]

# Slice to get elements from index 5 to the end
sliced_arr = arr[5:]
print(sliced_arr)  # Output: [ 6  7  8  9 10]


[3 4 5]
[2 4 6]
[ 6  7  8  9 10]


In [19]:
#Multidimensional Array Indexing and Slicing:

In [19]:
import numpy as np

# Create a 2D NumPy array
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)

# Access an individual element
element = matrix[1, 2]  # Row 1, Column 2
print(element)  # Output: 6

# Slice to get the first two rows and all columns
sliced_matrix = matrix[:2, :]
print(sliced_matrix)
# Output:
# [[1 2 3]
#  [4 5 6]]

# Slice to get the last two columns and all rows
sliced_matrix = matrix[:, -2:]
print(sliced_matrix)
# Output:
# [[2 3]
#  [5 6]
#  [8 9]]


[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]
 [8 9]]


# Pandas

In [ ]:
# Installation: pip3 install pandas
#Importing Pandas: import pandas as pd

In [ ]:
#Pandas Series:

Creating a Pandas Series:

You can create a Pandas Series using the pd.Series() constructor or by converting a Python list,
NumPy array, or dictionary into a Series.

In [20]:
import pandas as pd

# Creating a Series from a list
data = [10, 20, 30, 40]
series = pd.Series(data)
print(series)


0    10
1    20
2    30
3    40
dtype: int64


In [23]:
#Accessing elements of a Series:
print(series[2])  # Access the element at index 2 (30)


30


In [21]:
import pandas as pd
import numpy as np

# Creating a NumPy array
numpy_array = np.array([10, 20, 30, 40])

# Creating a Pandas Series from the NumPy array
series_from_array = pd.Series(numpy_array)
print(series_from_array)


0    10
1    20
2    30
3    40
dtype: int32


In [25]:
import pandas as pd

# Creating a dictionary
data_dict = {'A': 100, 'B': 200, 'C': 300, 'D': 400}

# Creating a Pandas Series from the dictionary
series_from_dict = pd.Series(data_dict)
print(series_from_dict)


A    100
B    200
C    300
D    400
dtype: int64


In [27]:
# Creating a Pandas DataFrame:
You can create a DataFrame from various data sources, such as lists,
NumPy arrays, dictionaries, or by reading data from external files like CSV or Excel.

In [22]:
import pandas as pd

# Creating a DataFrame from a dictionary
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
}
df = pd.DataFrame(data)
print(df)


      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston


In [29]:
# Accessing a specific column
print(df['Name'])

# Accessing a specific cell
print(df.at[1, 'Age'])


0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: object
30


In [25]:
#Creating a Pandas DataFrame from Lists:
import pandas as pd

# Creating lists for data
names = ['Alice', 'Bob', 'Charlie', 'David']
ages = [25, 30, 35, 40]
cities = ['New York', 'Los Angeles', 'Chicago', 'Houston']

# Creating a DataFrame from lists
data = {'Name': names, 'Age': ages, 'City': cities}
df_from_lists = pd.DataFrame(data)
print(df_from_lists)


      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston


In [26]:
#Creating a Pandas DataFrame from NumPy Arrays:
import pandas as pd
import numpy as np

# Creating NumPy arrays
names = np.array(['Alice', 'Bob', 'Charlie', 'David'])
ages = np.array([25, 30, 35, 40])
heights = np.array([160, 175, 180, 170])

# Creating a DataFrame from NumPy arrays
data = {'Name': names, 'Age': ages, 'Height': heights}
df_from_arrays = pd.DataFrame(data)
print(df_from_arrays)


      Name  Age  Height
0    Alice   25     160
1      Bob   30     175
2  Charlie   35     180
3    David   40     170


In [27]:
#Reading Data from a CSV File:
import pandas as pd

# Reading data from a CSV file
df = pd.read_csv('employees.csv')

# Display the first few rows of the DataFrame
print(df.head(10))
print(df.columns)

Index(['EMPLOYEE_ID', 'FIRST_NAME', 'LAST_NAME', 'EMAIL', 'PHONE_NUMBER',
       'HIRE_DATE', 'JOB_ID', 'SALARY', 'COMMISSION_PCT', 'MANAGER_ID',
       'DEPARTMENT_ID'],
      dtype='object')


In [29]:
import pandas as pd

# Reading data from an Excel file
df = pd.read_excel('employee.xlsx', sheet_name='Sheet1')

# Display the first few rows of the DataFrame
print(df.head(2))


   emp_id first_name last_name  hire_date
0     100     Steven      King 2003-06-17
1     101      Neena   Kochhar 2005-09-21


In [30]:
#Filtering

import pandas as pd

# Create a sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 22, 35]}

df = pd.DataFrame(data)

# Filter rows where Age is greater than 25
filtered_df = df[df['Age'] > 25]
print(filtered_df)

    Name  Age
1    Bob   30
3  David   35


In [31]:
#Sorting
# Sort the DataFrame by Age in ascending order
sorted_df = df.sort_values(by='Age')
print(sorted_df)

# Sort the DataFrame by Age in descending order
sorted_df_desc = df.sort_values(by='Age', ascending=False)
print(sorted_df_desc)

      Name  Age
2  Charlie   22
0    Alice   25
1      Bob   30
3    David   35
      Name  Age
3    David   35
1      Bob   30
0    Alice   25
2  Charlie   22


In [32]:
#Aggregating
# Calculate the mean age
mean_age = df['Age'].mean()
print(mean_age)
# Group by Name and calculate the mean age for each group
grouped_df = df.groupby('Name')['Age'].mean()


28.0


In [36]:
#Step 1: Handling Missing Values
import pandas as pd
import numpy as np

# Create a sample DataFrame with missing values
data = {'A': [1, 2, np.nan, 4],
        'B': [5, np.nan, np.nan, 8],
        'C': [9, 10, 11, 12]}

df = pd.DataFrame(data)
print(df)

# Remove rows with any missing values
df_cleaned = df.dropna()
print(df_cleaned)

# Fill missing values with a specific value (e.g., mean of the column)
mean_A = df['A'].mean()
print(mean_A)

df_filled = df.fillna({'A': mean_A, 'B': 0})
print(df_filled)

     A    B   C
0  1.0  5.0   9
1  2.0  NaN  10
2  NaN  NaN  11
3  4.0  8.0  12
     A    B   C
0  1.0  5.0   9
3  4.0  8.0  12
2.3333333333333335
          A    B   C
0  1.000000  5.0   9
1  2.000000  0.0  10
2  2.333333  0.0  11
3  4.000000  8.0  12


In [38]:
#Step 2: Removing Duplicates
# Create a sample DataFrame with duplicate rows
data = {'A': [1, 2, 2, 3],
        'B': [4, 5, 5, 6]}

df = pd.DataFrame(data)
print(df)

# Remove duplicate rows
df_no_duplicates = df.drop_duplicates()
print(df_no_duplicates)

   A  B
0  1  4
1  2  5
2  2  5
3  3  6
   A  B
0  1  4
1  2  5
3  3  6


In [39]:
#Step 3: Filtering and Subsetting Data

# Filter rows where column 'A' is greater than 1
filtered_df = df[df['A'] > 1]
print(filtered_df)
# Subset specific columns
subset_df = df[['A', 'B']]
print(subset_df)

   A  B
1  2  5
2  2  5
3  3  6
   A  B
0  1  4
1  2  5
2  2  5
3  3  6


In [40]:
#Step 4: Sorting Data
# Sort the DataFrame by column 'A' in descending order
sorted_df = df.sort_values(by='A', ascending=False)
print(sorted_df)

   A  B
3  3  6
1  2  5
2  2  5
0  1  4


In [42]:
#Step 5: Aggregating and Summarizing
# Calculate the mean of column 'B'
mean_B = df['B'].mean()
print(mean_B)
# Group by column 'A' and calculate the sum of column 'B' for each group
grouped_df = df.groupby('A')['B'].sum()
print(grouped_df)

5.0
A
1     4
2    10
3     6
Name: B, dtype: int64


In [41]:
#Step 6: Feature Engineering
# Create a new column 'A_squared' as a square of column 'A'
df['A_squared'] = df['A'] ** 2
print(df['A_squared'])

0    1
1    4
2    4
3    9
Name: A_squared, dtype: int64
